---
# file: roles/common/tasks/main.yml
- name: selinux check
  command: getenforce
  register: is_selinux_disabled
  failed_when: is_selinux_disabled.rc != 0
  changed_when: is_selinux_disabled.stdout != "Disabled"

- name: disable selinux
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=disabled/' /etc/selinux/config
  when: is_selinux_disabled.stdout != "Disabled"

- name: reboot after change selinux
  shell: /sbin/reboot
  when: is_selinux_disabled.stdout != "Disabled"

- name: wait for the server to go down (reboot)
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  when: is_selinux_disabled.stdout != "Disabled"

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22
  when: is_selinux_disabled.stdout != "Disabled"

- name: disable services
  service: name={{item}} state=stopped enabled=no
  with_items:
    - iptables
    - ip6tables

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - openssh-clients
    - ntp

- name: add ulimits settings
  template: src=enableulimit.sh.j2 dest=/etc/profile.d/enableulimit.sh owner=root group=root mode=0644

- name: ntp step-tickers settings
  template: src=etc_ntp_step-tickers.j2 dest=/etc/ntp/step-tickers owner=root group=root mode=0644
  notify:
    - ntpd restart

- name: ntp.conf settings
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:
    - ntpd restart

- name: /etc/sysconfig/ntpd settings
  template: src=etc_sysconfig_ntpd.j2 dest=/etc/sysconfig/ntpd owner=root group=root mode=0644
  notify:
    - ntpd restart

- name: ntpd running check
  command: service ntpd status
  register: running_ntpd
  failed_when: running_ntpd.rc not in [0,1,3]
  changed_when: running_ntpd.rc != 0

- name: run ntpdate
  service: name=ntpdate state=started
  when: running_ntpd.rc == 1

- name: enable ntpdate service
  service: name=ntpdate enabled=yes

- name: enable ntpd services
  service: name=ntpd state=started enabled=yes
